// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using REST_EF_MVC;

namespace REST_EF_MVC.Migrations
{
    [DbContext(typeof(PersonContext))]
    [Migration("20190612151532_CreatePersonDB")]
    partial class CreatePersonDB
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("REST_EF_MVC.Address", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("building");

                    b.Property<string>("city");

                    b.Property<string>("country");

                    b.Property<string>("flatNo");

                    b.Property<string>("street");

                    b.Property<string>("zip");

                    b.HasKey("id");

                    b.ToTable("addresses");
                });

            modelBuilder.Entity("REST_EF_MVC.Login", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("login");

                    b.Property<string>("passwd");

                    b.HasKey("id");

                    b.ToTable("logins");
                });

            modelBuilder.Entity("REST_EF_MVC.Person", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("addressid");

                    b.Property<string>("age");

                    b.Property<string>("email");

                    b.Property<string>("gender");

                    b.Property<int?>("loginid");

                    b.Property<string>("name");

                    b.Property<string>("phoneCode");

                    b.Property<string>("phoneNum");

                    b.Property<string>("surname");

                    b.HasKey("id");

                    b.HasIndex("addressid");

                    b.HasIndex("loginid");

                    b.ToTable("persons");
                });

            modelBuilder.Entity("REST_EF_MVC.Person", b =>
                {
                    b.HasOne("REST_EF_MVC.Address", "address")
                        .WithMany()
                        .HasForeignKey("addressid");

                    b.HasOne("REST_EF_MVC.Login", "login")
                        .WithMany()
                        .HasForeignKey("loginid");
                });
#pragma warning restore 612, 618
        }
    }
}
